namespace EPTG_Measurer_V3
{
    partial class ChooseStudyGroup
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewCheckBoxColumn gridViewCheckBoxColumn1 = new Telerik.WinControls.UI.GridViewCheckBoxColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn3 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.TableViewDefinition tableViewDefinition1 = new Telerik.WinControls.UI.TableViewDefinition();
            this.gridStudy = new Telerik.WinControls.UI.RadGridView();
            this.panel1 = new System.Windows.Forms.Panel();
            this.studyGroupsBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.btnLoad = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.gridStudy)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridStudy.MasterTemplate)).BeginInit();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.studyGroupsBindingSource)).BeginInit();
            this.SuspendLayout();
            // 
            // gridStudy
            // 
            this.gridStudy.BackColor = System.Drawing.SystemColors.Control;
            this.gridStudy.Cursor = System.Windows.Forms.Cursors.Default;
            this.gridStudy.Dock = System.Windows.Forms.DockStyle.Fill;
            this.gridStudy.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.gridStudy.ForeColor = System.Drawing.SystemColors.ControlText;
            this.gridStudy.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.gridStudy.Location = new System.Drawing.Point(0, 0);
            this.gridStudy.Margin = new System.Windows.Forms.Padding(5);
            // 
            // 
            // 
            this.gridStudy.MasterTemplate.AllowAddNewRow = false;
            this.gridStudy.MasterTemplate.AllowCellContextMenu = false;
            this.gridStudy.MasterTemplate.AllowColumnChooser = false;
            this.gridStudy.MasterTemplate.AllowColumnHeaderContextMenu = false;
            this.gridStudy.MasterTemplate.AllowColumnReorder = false;
            this.gridStudy.MasterTemplate.AllowColumnResize = false;
            this.gridStudy.MasterTemplate.AllowDeleteRow = false;
            this.gridStudy.MasterTemplate.AllowDragToGroup = false;
            this.gridStudy.MasterTemplate.AllowEditRow = false;
            this.gridStudy.MasterTemplate.AutoSizeColumnsMode = Telerik.WinControls.UI.GridViewAutoSizeColumnsMode.Fill;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "Id";
            gridViewDecimalColumn1.HeaderText = "Id";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.MinWidth = 8;
            gridViewDecimalColumn1.Name = "Id";
            gridViewDecimalColumn1.Width = 78;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "StudyName";
            gridViewTextBoxColumn1.HeaderText = "StudyName";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.MinWidth = 8;
            gridViewTextBoxColumn1.Name = "StudyName";
            gridViewTextBoxColumn1.Width = 266;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "Creator";
            gridViewTextBoxColumn2.HeaderText = "Creator";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.MinWidth = 8;
            gridViewTextBoxColumn2.Name = "Creator";
            gridViewTextBoxColumn2.Width = 266;
            gridViewCheckBoxColumn1.EnableExpressionEditor = false;
            gridViewCheckBoxColumn1.FieldName = "StudyFinished";
            gridViewCheckBoxColumn1.HeaderText = "StudyFinished";
            gridViewCheckBoxColumn1.IsAutoGenerated = true;
            gridViewCheckBoxColumn1.MinWidth = 31;
            gridViewCheckBoxColumn1.Name = "StudyFinished";
            gridViewCheckBoxColumn1.Width = 267;
            gridViewTextBoxColumn3.DataType = typeof(System.Collections.Generic.ICollection<EPTG_Measurer_V3.Database.PatientStudyGroup>);
            gridViewTextBoxColumn3.EnableExpressionEditor = false;
            gridViewTextBoxColumn3.FieldName = "PatientStudyGroup";
            gridViewTextBoxColumn3.HeaderText = "PatientStudyGroup";
            gridViewTextBoxColumn3.IsAutoGenerated = true;
            gridViewTextBoxColumn3.IsVisible = false;
            gridViewTextBoxColumn3.MinWidth = 8;
            gridViewTextBoxColumn3.Name = "PatientStudyGroup";
            gridViewTextBoxColumn3.Width = 78;
            this.gridStudy.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2,
            gridViewCheckBoxColumn1,
            gridViewTextBoxColumn3});
            this.gridStudy.MasterTemplate.DataSource = this.studyGroupsBindingSource;
            this.gridStudy.MasterTemplate.ViewDefinition = tableViewDefinition1;
            this.gridStudy.Name = "gridStudy";
            this.gridStudy.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.gridStudy.Size = new System.Drawing.Size(823, 463);
            this.gridStudy.TabIndex = 0;
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.btnLoad);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(0, 338);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(823, 125);
            this.panel1.TabIndex = 1;
            // 
            // studyGroupsBindingSource
            // 
            this.studyGroupsBindingSource.DataSource = typeof(EPTG_Measurer_V3.Database.StudyGroups);
            // 
            // btnLoad
            // 
            this.btnLoad.Location = new System.Drawing.Point(635, 38);
            this.btnLoad.Name = "btnLoad";
            this.btnLoad.Size = new System.Drawing.Size(128, 45);
            this.btnLoad.TabIndex = 0;
            this.btnLoad.Text = "Load";
            this.btnLoad.UseVisualStyleBackColor = true;
            this.btnLoad.Click += new System.EventHandler(this.btnLoad_Click);
            // 
            // ChooseStudyGroup
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(823, 463);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.gridStudy);
            this.Name = "ChooseStudyGroup";
            this.Text = "ChooseStudyGroup";
            ((System.ComponentModel.ISupportInitialize)(this.gridStudy.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.gridStudy)).EndInit();
            this.panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.studyGroupsBindingSource)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView gridStudy;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.BindingSource studyGroupsBindingSource;
        private System.Windows.Forms.Button btnLoad;
    }
}